services:
  ### Recommender API
  api:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    command: python main.py --port 8000 --model ./model
    working_dir: "/root/"
    ports:
      - 8000:8000
    volumes:
      - "./:/root/"

volumes:
  api:
networks:
  default:
    name: recommender-network
    external: true